version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install git wget curl unace unrar zip unzip p7zip-full p7zip-rar rename sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev python3-pip brotli liblz4-tool axel gawk aria2 detox
           pip3 install backports.lzma protobuf pycrypto docopt zstandard twrpdtgen
           git clone https://github.com/ItsVixano/Dump-maker dump
           cd dump
           curl -o .githubtoken $APIGIT
           curl -o .tgtoken $APIBOT
           bash dumpyara.sh https://assorted.downloads.oppo.com/firmware/CPH1919/CPH1919EX_11_OTA_1330_all_ST987r8zTmUH.ozip
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
