version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install git wget curl unace unrar zip unzip p7zip-full p7zip-rar rename sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev python3-pip brotli liblz4-tool axel gawk aria2 aptitude detox
           pip3 install backports.lzma protobuf pycrypto docopt zstandard twrpdtgen
           git clone https://github.com/Maitreya29/dumper dump
           cd dump
           echo $APIGIT
           echo $APIBOT
           export APIGIT=$APIGIT
           export APIBOT=$APIBOT
           curl -o .githubtoken $APIGIT
           curl -o .tgtoken $APIBOT
           export NAMEDUMP=Sweet
           bash dumpyara.sh https://bigota.d.miui.com/V12.0.4.0.RKFIDXM/miui_SWEETIDGlobal_V12.0.4.0.RKFIDXM_2e22fc6bc2_11.0.zip
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
